### ISSUE TITLE
Installation Failed on Big Sur

### ISSUE THREAD

**Issue by imofelrj** [fink/fink#219] opened 2020-12-16 13:02 UTC
When I am trying to install fink on macOS Big Sur, it shows me `11.1 does not match the expected value of 10.16. Please run fink selfupdate to download a newer version of fink at ~/Downloads/fink/perlmod/Fink/Services.pm line 1369.`. How can I fix this ? Thanks a lot.

**Comment by nieder** [comment] 2020-12-19 10:17
Yes, 11.1 completely broke how Fink detects the system version. I've been searching for a way to fix it.
Is this for a brand new Fink install on BigSur11.1, or did you already have an earlier version of macOS with Fink and upgraded to 11.1?
Also, what is the output of the terminal commands `sw_vers; uname -a` ?

**Comment by nieder** [comment] 2020-12-19 10:46
Also, are you setting `SYSTEM_VERSION_COMPAT=1` someplace in your environment?

**Comment by IMO-Au** [comment] 2020-12-19 11:52
@nieder No, I haven't.And this is a new computer which is based on x86.However after I ran `export SYSTEM_VERSION_COMPAT=1`, it still showed me the same message.

**Comment by nieder** [comment] 2021-01-08 11:13
The problem is how Apple is now tracking the darwin version relative to the macOS version on Big Sur. The fix is tracked here: https://github.com/TheSin-/fink/pull/6

**Comment by cooljeanius** [comment] 2021-02-09 17:23
> The problem is how Apple is now tracking the darwin version relative to the macOS version on Big Sur. The fix is tracked here: https://github.com/TheSin-/fink/pull/6

Looking forward to this getting merged when possible!

**Comment by daemonspudguy** [comment] 2021-08-08 20:46
Any updates on this?

**Comment by TheSin-** [comment] 2021-08-13 18:19
Everything is merged in my PR currently

**Comment by daemonspudguy** [comment] 2021-08-14 00:29
Yes, but that only applies to the dpkg1.16 branch. I still couldn't bootstrap that branch on my system, either.

**Comment by daemonspudguy** [comment] 2021-08-14 00:31
Can try to bootstrap it right now anyways, my power is out and I can only use my phone because of it.

**Comment by daemonspudguy** [comment] 2021-08-14 01:06
My power is back. Time to try now.

**Comment by daemonspudguy** [comment] 2021-08-14 01:27
It failed building dpkg-bootstrap. I have created a log of the bootstrap script running make.
[dpkg-bootstrap-make.log](https://github.com/fink/fink/files/6985721/dpkg-bootstrap-make.log)

**Comment by daemonspudguy** [comment] 2021-08-16 16:15
@TheSin- I can't bootstrap your branch. It fails with the output I uploaded previously.

**Comment by TheSin-** [comment] 2021-08-16 16:20
you are going to have to wait for @nieder as I don't have access o BigSur yet, so I rely on his tests atm

**Comment by cooljeanius** [comment] 2021-08-16 16:26
I'm currently using Big Sur, so theoretically I could test, but it might take me a while to get back up to speed with Fink; it's been a while since I last did anything with it...

**Comment by TheSin-** [comment] 2021-08-16 16:28
@nieder has done all the bigger work to date on BigSur, might be best to wait for him to look it over cause last I knew it was working so it could just be an issue with @daemonspudguy install, maybe something in /usr/local causing breakage?

**Comment by daemonspudguy** [comment] 2021-08-16 16:37
I have homebrew and ZSH installed. I don't have anything perl related installed with brew to my knowledge.

**Comment by dmacks** [comment] 2021-08-16 16:38
Unrelately, might be useful to patch-out -Wlogical-op so we can see relevant diagnostics more easily.

**Comment by TheSin-** [comment] 2021-08-16 16:57
@dmacks, agreed, but that's just convince.

@daemonspudguy anything installed CAN cause issues, it's error's on making the intl files for the po (manpages) which is a very odd issue and should not happen.  We'd likely have to build it on a clean system first to make sure it builds and if it does figure out what it's picking up on your system to cause issues.  there might be more in the config.log if it's picking this up in /usr/local that would show there.  The other option is to check your path, if you have home-brew it could be using utils from there to create the po files which cause be the issue.

Try a bootstrap but remove all PATH entries for brew before hand perhaps?  Mixing package management systems is always a PITA.  Since I do not use brew (I make a symlink in my system to fink ;)) I have no idea how it works or what could be conflicting

**Comment by daemonspudguy** [comment] 2021-08-16 21:51
tried that with niedler's repo. Same issue.

**Comment by daemonspudguy** [comment] 2021-08-16 21:56
I'm now gonna try to install fink now that I removed homebrew from my system

**Comment by daemonspudguy** [comment] 2021-08-17 01:01
IT BOOTSTRAPPED!

**Comment by TheSin-** [comment] 2021-08-17 01:31
so we know it's something in brew, but now we need to know what so I can fix it to work together ;)

I guess I'll make a VM with BigSur and install brew then it, but I might need to know what you had installed with brew to make it fail, would you have a list per chance that you can share?

**Comment by daemonspudguy** [comment] 2021-08-17 01:37
Nope. Brew is removed now. But I can say that I had python, Cakebrew, zsh, and that's about it.

**Comment by daemonspudguy** [comment] 2021-08-17 19:10
The only issue I have is that several packages require texinfo, which doesn't exist.

**Comment by TheSin-** [comment] 2021-08-17 19:15
texinfo is part of the bootstrap so it exists, you can't even bootstrap without it.

what does `fink list texinfo` show?

**Comment by daemonspudguy** [comment] 2021-08-17 19:15
A package called texinfo-legacy.

**Comment by TheSin-** [comment] 2021-08-17 19:16
should look like

```
Information about 11732 packages read in 2 seconds.
 i   texinfo          6.5-302      GNU documentation system
     texinfo-legacy   4.13-1       GNU documentation system (legacy support)
```

**Comment by daemonspudguy** [comment] 2021-08-17 19:17
Okay, that's odd.

**Comment by TheSin-** [comment] 2021-08-17 19:18
wait I might know why one sec

**Comment by TheSin-** [comment] 2021-08-17 19:19
there is a texinfo for 11.0 and 11.3, you are on 11.5 maybe something is wrong the 11.3 version isn't extending to 11.5?  We will need to wait for @nieder for that one.

**Comment by daemonspudguy** [comment] 2021-08-17 19:20
It recognizes the distro as 11.3, despite me being on 11.5.1

**Comment by daemonspudguy** [comment] 2021-08-17 19:22
There is no texinfo-11.3.info only 11.0

**Comment by TheSin-** [comment] 2021-08-17 19:23
in my PR there is a 11.3

https://github.com/TheSin-/fink/blob/dpkg1.16/10.9-libcxx/texinfo-11.3.info

**Comment by daemonspudguy** [comment] 2021-08-17 19:24
Ok that's really strange. I used that when I bootstrapped.

**Comment by daemonspudguy** [comment] 2021-08-17 19:24
Ok that's really strange. I used that when I bootstrapped.

**Comment by TheSin-** [comment] 2021-08-17 19:27
you might have to copy it to your local dist and see if that fixes it.

**Comment by TheSin-** [comment] 2021-08-17 19:28
looks like it's not in live yet likely do to no official support yet.  But you can copy it into local for now from the checkout you used.

**Comment by daemonspudguy** [comment] 2021-08-17 19:28
I just went ahead and copied it.

**Comment by TheSin-** [comment] 2021-08-17 19:31
after a fink index does it now show properly as avail?

**Comment by daemonspudguy** [comment] 2021-08-17 19:31
Yep, and is installed.

**Comment by daemonspudguy** [comment] 2021-08-18 01:22
Anyone know why libical can't find symbols for x86_64?

**Comment by daemonspudguy** [comment] 2021-08-18 02:54
@TheSin- how do you have 11732 packages? I have 11401.

**Comment by TheSin-** [comment] 2021-08-18 02:59
My experimental repo.

**Comment by daemonspudguy** [comment] 2021-08-18 03:01
I'm gonna guess it isn't public.

**Comment by dmacks** [comment] 2021-08-18 03:19
> Anyone know why libical can't find symbols for x86_64?

That's pretty vague (no compiler call or actual error message) and seemingly different than this Issue about installation/bootstrapping. Please open a new issue for it with full detail.

**Comment by daemonspudguy** [comment] 2021-08-18 03:20
> That's pretty vague (no compiler call or actual error message) and seemingly different than this Issue about installation/bootstrapping. Please open a new issue for it with full detail.


I will go add the issue.

**Comment by cooljeanius** [comment] 2021-10-21 13:55
> I'm closing this because the original problem with macOS 11.1 is fixed in the dpkg1.16 branch and the libical problem was fixed in [fink/fink-distributions#847](https://github.com/fink/fink-distributions/issues/847).

Hi, the latest news entry on [the website](https://finkproject.org/) (for the 0.45.3 release) still says "This release does not yet support macOS 11 (Big Sur)." Could this be left open until a new release is made? Or, at least until the dpkg1.16 branch is merged into master?

**Comment by cooljeanius** [comment] 2023-04-02 05:09
> I keep meaning to add a new note to the front page about how to get the dpkg1.16 branch for BigSur support.

Have you gotten around to adding this note yet?

**Comment by TheSin-** [comment] 2023-04-02 20:48
Why add a note which makes things more complex, why not just merge if it’s the official path?

**Comment by nieder** [comment] 2023-07-29 10:05
Closing with #66 merged, which supports Big Sur (and Monterey and Ventura).

**Closed by nieder** 2023-07-29 10:05 UTC
Labels: Bootstrap
