### ISSUE TITLE
Several fink commands fail with "Failed: not a reference at /opt/sw/lib/perl5/Fink/Services.pm line 2045."

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink#259] opened 2023-10-08 20:56 UTC
Specifically, `fink selfupdate`, `fink update-all`, and `fink cleanup --all` currently all fail with the following error for me:
```
Failed: not a reference at /opt/sw/lib/perl5/Fink/Services.pm line 2045.
```
(Probably other commands would fail similarly, but I haven't tested.)
I can think of a few things I did that might have caused this:
1. I switched branches in the fink-distributions repo (using the GitHub Desktop GUI) to check out its PR 29: fink/fink-distributions#29. Then I switched branches back to master.
2. I ran `fink plugins`, noticed that it failed partway through (after listing the CVS selfupdate-method) with `Failed: can't write temporary file: Permission denied at /opt/sw/lib/perl5/Fink/Config.pm line 623.`, and then re-ran the command with `sudo` to get it to print the rest of its output.
Before:
```
$ fink plugins
Notification Plugins:

    Growl           1           Growl on-screen notification
                                http://www.growl.info/
 !  QuickSilver     1           QuickSilver on-screen notification
                                http://quicksilver.blacktree.com/
 !  Say             1           Text-to-speech audible notification
 !  Syslog          1           Log notifications to /var/log/system.log
 !  XTerm           1           Terminal title-bar notification

Checksum Plugins:

 i  MD5             1           MD5 checksum
 i  SHA1            1           SHA1 checksum
 i  SHA256          1           SHA256 checksum

Selfupdate-Method Plugins:

 +  CVS             1.01        cvs
Failed: can't write temporary file: Permission denied at /opt/sw/lib/perl5/Fink/Config.pm line 623.
```
After:
```
$ sudo fink plugins
Password:
Notification Plugins:

    Growl           1           Growl on-screen notification
                                http://www.growl.info/
 !  QuickSilver     1           QuickSilver on-screen notification
                                http://quicksilver.blacktree.com/
 !  Say             1           Text-to-speech audible notification
 !  Syslog          1           Log notifications to /var/log/system.log
 !  XTerm           1           Terminal title-bar notification

Checksum Plugins:

 i  MD5             1           MD5 checksum
 i  SHA1            1           SHA1 checksum
 i  SHA256          1           SHA256 checksum

Selfupdate-Method Plugins:

 +  CVS             1.01        cvs
 +i git             1           git
Fink does not presently support switching to selfupdate-point from any other selfupdate method
 -  point           1           Stick to point releases
 +  rsync           1           rsync
 +  svn             1           svn

```
Looking at line 2045 in `Services.pm`, it currently says:
```perl
	if (Storable::store($ref, $tmp)) {
```
...and the two variables there are from a few lines above:
```perl
	my ($ref, $file) = @_;
	my ($dummy, $tmp) = tempfile("$file.XXXXX");

	return 0 unless eval { require Storable };
```
So I guess this means there was some sort of issue with creating the tempfile?

**Comment by nieder** [comment] 2023-10-10 10:42
@dmacks @TheSin- 

Maybe adding some print commands above that if to see the contents of $ref and $tmp could help figure out what's not being set before the conditional at line 2045 (I think that's the meaning of that error).

**Comment by TheSin-** [comment] 2023-10-10 20:56
I just fixed a tempfile call in f-v-p I'll have a look at this one as well

**Comment by TheSin-** [comment] 2023-10-10 21:03
these all look like perm issues, like sudo isn't being used, but still trying to reproduce it (as I do not want to run cleanup)

**Comment by TheSin-** [comment] 2023-10-10 21:05
it's 100% a perms issue, I could reproduce it with `fink plugins`, but `sudo fink plugins` works.  It's trying to make a tmp file in a place the user can not write.

Try `sudo fink cleanup --all` for me and see if that works

**Comment by TheSin-** [comment] 2023-10-10 22:50
okay so that call differs then.  I'll keep digging.  Thanks

**Comment by cooljeanius** [comment] 2023-10-10 22:54
> okay so that call differs then. I'll keep digging. Thanks

If you patched something that was supposed to make it work, it's possible that I don't have that change due to selfupdate not working for me currently...

**Comment by TheSin-** [comment] 2023-10-10 23:07
I didn't I just don't want to run that command so I wanted to make sure sudo didn't fix it like the `plugins` command.  I figured it was different but since I don't want to run it, it makes debugging it very difficult.

**Comment by TheSin-** [comment] 2023-10-10 23:29
wait you can't do a `selfupdate`? that means you might not have a package list.  That could be the issue.  `store_rename` is only used 3 times, and each time the ref is based on haven't a list of info files.

in Package.pm can you add a unique print before each call to `store_rename` so I know which of the 3 it is?

**Comment by cooljeanius** [comment] 2023-10-10 23:56
> wait you can't do a `selfupdate`? that means you might not have a package list. That could be the issue. `store_rename` is only used 3 times, and each time the ref is based on haven't a list of info files.
> 
> in Package.pm can you add a unique print before each call to `store_rename` so I know which of the 3 it is?
> 

Could you send me a diff to apply? I don't really trust myself to do it properly myself...

> they might just need some safe guards before making the call.
> 
> my guess is that it's
> 
> ```
> # Store the proxy db
>                 if ($ops{write} && !$config->custom_treelist) {
>                         store_rename($packages, $class->db_proxies);
>                 }
> ```
> 
> might be nice to print `$packages` and `$class->db_proxies`
> 
> ```
> # Store the proxy db
>                 if ($ops{write} && !$config->custom_treelist) {
> printf "-> %s -> %s\n", $packages,  $class->db_proxies;
>                         store_rename($packages, $class->db_proxies);
>                 }
> ```
> 
> for the record `fink cleanup --all -d` works for me, hence why I assume it's cause your broken `selfupdate`
> 
> just bit the bullet and ran `fink cleanup --all` and it works perfectly for me.

**Comment by TheSin-** [comment] 2023-10-10 23:58
sure I'll try to build one tomorrow, doing updates tonight so my cycles are limited.

**Comment by TheSin-** [comment] 2023-10-11 05:54
could you post the full output of `fink cleanup --all` please?

I'm wondering if you see

`Scanning package description files` first, as if this is the case it's cause you have no info files that it's failing which means we need to fix your dists issue first.

**Comment by cooljeanius** [comment] 2023-10-11 20:24
> could you post the full output of `fink cleanup --all` please?

I already did, above

**Comment by TheSin-** [comment] 2023-10-11 20:27
okay then that looks like this is caused because of your dist issue, there is nothing fix per say, it'll be fixed once you fix the %p/fink/dists linking

Please fix that first, this will just work, it because fink sees 0 info files and has nothing to idx.

**Comment by cooljeanius** [comment] 2023-10-11 20:31
> okay then that looks like this is caused because of your dist issue, there is nothing fix per say, it'll be fixed once you fix the %p/fink/dists linking

Well a more informative error message would be useful, at least...

> 
> Please fix that first, this will just work, it because fink sees 0 info files and has nothing to idx.

```
$ readlink /opt/sw/fink/dists 
11.3
```
Ah ok that explains it, I saw a file named "`11.3`" show up in my GitHub Desktop GUI and assumed that it wasn't supposed to be tracked, so I deleted it; guess I'll put it back... maybe an additional fix would be to update the `.gitignore` as well?

**Comment by cooljeanius** [comment] 2023-10-11 20:34
ok I'm confirming that putting that directory back fixed things for me; I still think that the error message could be improved, though...

**Comment by TheSin-** [comment] 2023-10-11 20:40
it's not about informative, this is something that should never happen.  For example this is the first time in 20 years, our resources (man hours) are very limited, something that needs this much work for something that might happen 1 time in 20 years isn't really a focal.  I'd much rather move to try to figure out why your dists didn't relink instead.

**Comment by cooljeanius** [comment] 2023-10-11 20:50
> it's not about informative, this is something that should never happen. 

If there's one thing I've learned from the tech world over the last few decades, it's that things that "should never happen" can and do actually happen; I consider defensive programming to be good practice, and would encourage it.

> I'd much rather move to try to figure out why your dists didn't relink instead.

Well how exactly are they supposed to get relinked if things were functioning properly, anyways?

**Comment by TheSin-** [comment] 2023-10-11 20:50
if you rerun `inject.pl` it should fix your dists link

```
Checking system... aarch64-apple-darwin22.6.0
This system is supported and tested.
ln -s 13.0 /opt/sw/fink/dists
```

I'm also committing a fix for this issue right now since I did all the work to track it :D

**Comment by TheSin-** [comment] 2023-10-11 20:53
fixed

**Closed by TheSin-** 2023-10-11 20:53 UTC

**Comment by htodd** [comment] 2023-10-12 00:17
How much have you paid for fink? I haven't gotten a dime.

On Wed, 11 Oct 2023, Eric Gallager wrote:

>> it's not about informative, this is something that should never happen.
>
> If there's one thing I've learned from the tech world over the last few decades, it's that things that "should never happen" can and do actually happen; I consider defensive programming to be good practice, and would encourage it.
>
>> I'd much rather move to try to figure out why your dists didn't relink instead.
>
> Well how exactly are they supposed to get relinked if things were functioning properly, anyways?
>
>
>

-- 
Hisashi T Fujinaka - ***@***.***
BSEE + BSChem + BAEnglish + MSCS + $2.50 = coffee

**Comment by cooljeanius** [comment] 2023-10-12 01:42
If any of you accept payments via GitHub Sponsors or LiberaPay or OpenCollective or Patreon or PayPal, I will gladly send payments.
