### ISSUE TITLE
can't use apt-get on Mac 

### ISSUE THREAD

**Issue by dashishmeister** [fink/fink#231] opened 2021-06-19 13:13 UTC
trying to install a package, it throws this
I am already aware that there is no longer a bindist for fink on Mac
```redacted@redacted-for-privacy ~ % sudo apt-get install hollywood
Reading Package Lists... Done
Building Dependency Tree... Done
W: Couldn't stat source package list http://bindist.finkmirrors.net stable/main Packages (/opt/sw/var/lib/apt/lists/bindist.finkmirrors.net_10.15_dists_stable_main_binary-darwin-x86%5f64_Packages) - stat (2 No such file or directory)
W: Couldn't stat source package list http://bindist.finkmirrors.net stable/main Packages (/opt/sw/var/lib/apt/lists/bindist.finkmirrors.net_10.15_dists_stable_main_binary-darwin-x86%5f64_Packages) - stat (2 No such file or directory)
W: You may want to run apt-get update to correct these problems
E: Couldn't find package hollywood
```

apt-get update throws

```redacted@redacted-for-privacy ~ % sudo apt-get update
Err http://bindist.finkmirrors.net stable/main Packages
  404 Not Found
Hit http://bindist.finkmirrors.net stable/main Release
Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
Reading Package Lists... Done
Building Dependency Tree... Done
W: Couldn't stat source package list http://bindist.finkmirrors.net stable/main Packages (/opt/sw/var/lib/apt/lists/bindist.finkmirrors.net_10.15_dists_stable_main_binary-darwin-x86%5f64_Packages) - stat (2 No such file or directory)
W: Couldn't stat source package list http://bindist.finkmirrors.net stable/main Packages (/opt/sw/var/lib/apt/lists/bindist.finkmirrors.net_10.15_dists_stable_main_binary-darwin-x86%5f64_Packages) - stat (2 No such file or directory)
W: You may want to run apt-get update to correct these problems
E: Some index files failed to download, they have been ignored, or old ones used instead.
```

apt/sources.list

```# Local modifications should either go above this line, or at the end.
#
# Default APT sources configuration for Fink, written by the fink program

# Local package trees - packages built from source locally
# NOTE: this is automatically kept in sync with the Trees: line in
# /opt/sw/etc/fink.conf
# NOTE: run 'fink scanpackages' to update the corresponding Packages.gz files
deb file:/opt/sw/fink local main
deb file:/opt/sw/fink stable main

# Official binary distribution: download location for packages
# from the latest release
deb http://bindist.finkmirrors.net/10.15 stable main

# Put local modifications to this file below this line, or at the top.
```

fink.conf

```# Fink configuration, initially created by bootstrap
Basepath: /opt/sw
RootMethod: sudo
Trees: local/main stable/main
Distribution: 10.15
SelfUpdateTrees: 10.9-libcxx
AutoUid: false
ConfFileCompatVersion: 3
FinkBldUid: 600
MaxBuildJobs: 1
Mirror-apache: http://www.apache.org/dist
Mirror-apt: http://bindist.finkmirrors.net
Mirror-cpan: ftp://ftp.cpan.org/pub/CPAN
Mirror-ctan: ftp://tug.ctan.org/tex-archive
Mirror-debian: ftp://ftp.debian.org/debian
Mirror-freebsd: http://distcache.FreeBSD.org/ports-distfiles/
Mirror-gimp: http://download.gimp.org/mirror/pub/gimp
Mirror-gnome: http://ftp.gnome.org/pub/GNOME
Mirror-gnu: http://ftpmirror.gnu.org
Mirror-kde: http://download.kde.org/
Mirror-master: http://distfiles.master.finkmirrors.net/distfiles/
Mirror-rsync: rsync://distfiles.master.finkmirrors.net/finkinfo/
Mirror-sourceforge: http://downloads.sourceforge.net
MirrorContinent: eur
MirrorCountry: eur-fr
MirrorOrder: MasterFirst
ProxyPassiveFTP: true
UseBinaryDist: false
Verbose: 1
SelfUpdateMethod: rsync
```

**Comment by dak180** [comment] 2021-06-19 14:06
`apt-get` is not really meant to be called directly in a fink install; you should use the [fink tool](https://finkproject.org/doc/users-guide/uguide.en.html#usage) (or see the man page) its self. 

That said `hollywood` does not appear to be a package presently in fink.

**Comment by akhansen** [comment] 2021-06-19 15:24
Well, actually there are still some functionalities that `apt-get` has that aren't implemented in the `fink` tool (usually as a call to `apt-get`).  

That being said, we don't have a binary distribution for 10.15 at this time, so `apt-get` will only work for locally-built packages.

**Comment by akhansen** [comment] 2021-06-19 15:25
Closing because apt-get is functioning as intended, given the circumstances.

**Closed by akhansen** 2021-06-19 15:25 UTC
Labels: Question

**Comment by dmacks** [comment] 2021-06-19 18:01
I tried to create a package for it, and got as far as "it doesn't actually work". This seems a long-standing issue, per dustinkirkland/hollywood/issues/18

**Comment by dashishmeister** [comment] 2021-06-20 19:08
<img width="429" alt="Screenshot 2021-06-20 at 21 01 29" src="https://user-images.githubusercontent.com/75739987/122685432-9ae36880-d20b-11eb-9b26-11e510fb7ec3.png">

bruh change this

**Comment by akhansen** [comment] 2021-06-20 19:55
Might I suggest running "fink configure", and saying "no" to the "use binary packages" option?  That'll keep the apt error messages from  showing up.

**Comment by dashishmeister** [comment] 2021-06-26 09:34
I already did that
