### ISSUE TITLE
10.15 bootstrap problems using Xcode GM/Catalina 10.15b7

### ISSUE THREAD

**Issue by baelfeir** [fink/fink#197] opened 2019-09-03 09:54 UTC
Not sure if this is a known and already solved issue, but trying to bootstrap on 10.15 is failing (already worked around r-only root) with the following:

```
ftello.c:53:12: error: no member named '_flag' in 'struct __sFILE'; did you mean '_flags'?
  if (fp_->_flag & _IOWRT)
           ^~~~~
           _flags
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:130:8: note: '_flags' declared here
        short   _flags;         /* flags, below; this FILE is free if 0 */
                ^
ftello.c:53:20: error: use of undeclared identifier '_IOWRT'
  if (fp_->_flag & _IOWRT)
                   ^
ftello.c:64:21: error: no member named '_flag' in 'struct __sFILE'; did  CC       isnanf.o
 you mean '_flags'?
          if ((fp_->_flag & _IONBF) == 0 && fp_->_base != NULL)
                    ^~~~~
                    _flags
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:130:8: note: '_flags' declared here
        short   _flags;         /* flags, below; this FILE is free if 0 */
                ^
ftello.c:64:50: error: no member named '_base' in 'struct __sFILE'
          if ((fp_->_flag & _IONBF) == 0 && fp_->_base != NULL)
                                            ~~~  ^
ftello.c:65:25: error: no member named '_ptr' in 'struct __sFILE'
            pos += fp_->_ptr - fp_->_base;
                   ~~~  ^
ftello.c:65:37: error: no member named '_base' in 'struct __sFILE'
            pos += fp_->_ptr - fp_->_base;
                               ~~~  ^
6 errors generated.
make[3]: *** [ftello.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
### execution of make failed, exit code 2
phase compiling: gzip-1.9-1 failed

Before reporting any errors, please run "fink selfupdate" and try again.
Also try using "fink configure" to set your maximum build jobs to 1 and
attempt to build the package again.
If you continue to have issues, please check to see if the FAQ on Fink's
website solves the problem.  If not, ask on one (not both, please) of
these mailing lists:

	The Fink Users List <fink-users@lists.sourceforge.net>
	The Fink Beginners List <fink-beginners@lists.sourceforge.net>.

Please try to include the complete error message in your report.  This
generally consists of a compiler line starting with e.g. "gcc" or "g++"
followed by the actual error output from the compiler.

Also include the following system information:
Package manager version: 0.45.0
Distribution version: selfupdate-point (bootstrap), 10.15, x86_64
Trees: local/main stable/main
No recognized Xcode.app installed
Xcode command-line tools: 11.0.0.0.1.1565314599
Max. Fink build jobs:  4
ERROR: Bootstrap phase 2 failed!

```

-- After a little digging I found the problem with gzip. It's setting some archaic flag called 
FTELLO_BROKEN_AFTER_SWITCHING_FROM_READ_TO_WRITE to 1 which causes it to use a seriously modern-system-broken workaround for a solaris bug. I haven't given any more investigation as to why the flag is being set, but can confirm #undef'n it in lib/config.h allows the build to progress.

Thanks for all the work on 10.15

**Comment by nieder** [comment] 2019-09-03 11:56
Thanks for the detective work.

This is the relevant code in ftello.c:
````
#if FTELLO_BROKEN_AFTER_SWITCHING_FROM_READ_TO_WRITE /* Solaris */
  /* The Solaris stdio leaves the _IOREAD flag set after reading from a file
     reaches EOF and the program then starts writing to the file.  ftello
     gets confused by this.  */
  if (fp_->_flag & _IOWRT)
    {
      off_t pos;

      /* Call ftello nevertheless, for the side effects that it does on fp.  */
      ftello (fp);

      /* Compute the file position ourselves.  */
      pos = lseek (fileno (fp), (off_t) 0, SEEK_CUR);
      if (pos >= 0)
        {
          if ((fp_->_flag & _IONBF) == 0 && fp_->_base != NULL)
            pos += fp_->_ptr - fp_->_base;
        }
      return pos;
    }
#endif
````

Can you paste the output from ./configure that references ftello?
And in your build directory, can you look at the file /opt/sw/build.build/gzip-1.9-1/gzip-1.9/lib/config.h and search for sections that reference ftello? 

I get this on 10.13/Xcode10.1:
```
checking whether lstat correctly handles trailing slash... no
checking whether ftello is declared... yes
checking for ftello... yes
checking whether ftello works... yes
checking whether getcwd (NULL, 0) allocates memory for result... yes
```
```
/* Define to 1 if the system's ftello function has the Solaris bug. */
/* #undef FTELLO_BROKEN_AFTER_SWITCHING_FROM_READ_TO_WRITE */
...
/* Define to 1 when the gnulib module ftello should be tested. */
#define GNULIB_TEST_FTELLO 1
...
/* Define to 1 if you have the declaration of `ftello', and to 0 if you don't.
   */
#define HAVE_DECL_FTELLO 1
...
/* Define to 1 if fseeko (and presumably ftello) exists and is declared. */
#define HAVE_FSEEKO 1
```

It's that last `checking whether ftello works` from configure test that determines if FTELLO_BROKEN_AFTER_SWITCHING_FROM_READ_TO_WRITE set.

**Comment by baelfeir** [comment] 2019-09-04 15:49
Instead of finding all these piecemeal things and risk leaving out other important information you may need, I've zipped up the broken gzip-1.9 from src/fink.build

Thanks again!

[gzip-1.9.zip](https://github.com/fink/fink/files/3575390/gzip-1.9.zip)

**Comment by nieder** [comment] 2019-09-04 16:52
Thanks. This the the relevant part from your config.log:
```
configure:12785: checking whether ftello is declared
configure:12785: gcc -c -g -O2 -I/sw/include conftest.c >&5
configure:12785: $? = 0
configure:12785: result: yes
configure:12808: checking for ftello
configure:12826: gcc -o conftest -g -O2 -I/sw/include -L/sw/lib conftest.c  >&5
configure:12826: $? = 0
configure:12836: result: yes
configure:12849: checking whether ftello works
configure:12929: gcc -o conftest -g -O2 -I/sw/include -L/sw/lib conftest.c  >&5
configure:12929: $? = 0
configure:12929: ./conftest
configure:12929: $? = 6
configure: program exited with status 6
```
But they didn't bother to say WHY the test program failed :( There's also gzip-1.10 now. I'll try to test that to see if it deals with the problem.

**Comment by nieder** [comment] 2019-09-05 10:10
I managed to get a VM with Xcode11b7 and can reproduce the problem. Unfortunately, gzip-1.10 doesn't fix it. Also, I can build the test program (see below) and run it, and the problem is repeated, but I have no clue on how to diagnose the output from it.

Also, if I build the test program on 10.13, it works there but fails when I copy the executable to 10.15b. So it seems that something is wrong at the macOS level with the latest beta.

**Comment by nieder** [comment] 2019-09-05 10:32
This is the test program.
```
/* end confdefs.h.  */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define TESTFILE "conftest.tmp"
int
main (void)
{
  FILE *fp;

  /* Create a file with some contents.  */
  fp = fopen (TESTFILE, "w");
  if (fp == NULL)
    return 70;
  if (fwrite ("foogarshh", 1, 9, fp) < 8)
    { fclose (fp); return 71; }
  if (fclose (fp))
    return 72;

  /* The file's contents is now "foogarsh".  */

  /* Try writing after reading to EOF.  */
  fp = fopen (TESTFILE, "r+");
  if (fp == NULL)
    return 73;
  if (fseek (fp, -1, SEEK_END))
    { fclose (fp); return 74; }
  if (!(getc (fp) == 'h'))
    { fclose (fp); return 1; }
  if (!(getc (fp) == EOF))
    { fclose (fp); return 2; }
  if (!(ftell (fp) == 8))
    { fclose (fp); return 3; }
  if (!(ftell (fp) == 8))
    { fclose (fp); return 4; }
  if (!(putc ('!', fp) == '!'))
    { fclose (fp); return 5; }
  if (!(ftell (fp) == 9))
    { fclose (fp); return 6; }
  if (!(fclose (fp) == 0))
    return 7;
  fp = fopen (TESTFILE, "r");
  if (fp == NULL)
    return 75;
  {
    char buf[10];
    if (!(fread (buf, 1, 10, fp) == 9))
      { fclose (fp); return 10; }
    if (!(memcmp (buf, "foogarsh!", 9) == 0))
      { fclose (fp); return 11; }
  }
  if (!(fclose (fp) == 0))
    return 12;

  /* The file's contents is now "foogarsh!".  */

  return 0;
}
```
To compile and run, save as `conftest.c`:
```
gcc -o conftest -g -O2 -I/sw/include -L/sw/lib conftest.c
./conftest ; echo $?; cat conftest.tmp
```
The output code should be '0', not '6', and conftest.tmp should be `foogarsh!`, not `foogarsh`. I think something is wrong with the `putc` function, but I don't know what.

**Comment by baelfeir** [comment] 2019-09-05 14:57
One thing that might be going on: There was a big alert sent that the latest Catalina beta (10.15 Beta 7) breaks compatibility with all previous Xcode 11 betas, thus requiring Xcode 11 Beta 7. However, they never released Xcode command line tools beta 7, so what ever this incompatibility is, this may be how it's expressing itself. Let me try this again when Apple gets the !@#* in order and syncs up versions.  

This might be a red herring.

**Comment by nieder** [comment] 2019-09-14 01:13
What happens if you add `ac_cv_have_decl_ftello=yes` to the beginning of line 16 of the gzip.info line?

**Comment by nieder** [comment] 2019-09-14 11:52
Actually, try `gl_cv_func_ftello_works=yes` instead.

**Comment by baelfeir** [comment] 2019-09-15 07:05
Added this to gzip.info found at: ./fink/10.9-libcxx/stable/main/finkinfo/base/gzip.info

``
CompileScript: <<
 gzip_cv_assembler=no gl_cv_func_ftello_works=yes ./configure %c
 make all
<<
``

Happy to report a success when it comes to gzip. It's still bootstrapping. Ill add another update.

**Comment by baelfeir** [comment] 2019-09-15 12:25
Oh, to note: Xcode and many other things need to be given "full access to the disk" via the privacy setting. Xquartz failed to install automatically and this was my reaction to it. 
<img width="687" alt="Screen Shot 2019-09-15 at 7 23 48 AM" src="https://user-images.githubusercontent.com/54841744/64921523-02909800-d78a-11e9-92d6-802372987d2b.png">
Attached an example screenshot:

**Comment by baelfeir** [comment] 2019-09-15 12:42
Durr, its a binary package thing. I'll read the fink-devel mailing lists to see what to do about that.

**Comment by nieder** [comment] 2019-09-15 12:55
> Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
> Reading Package Lists...
> Building Dependency Tree...
> E: Some index files failed to download, they have been ignored, or old ones used instead.
> ### execution of /sw/bin/apt-get-lockwait failed, exit code 100
> WARNING: Failure while updating indexes.
> ```
> 
> I think its just a mirror problem. I'll try another and play around.

There's no 10.15 binary distribution yet, so it will error out to 404.

**Comment by baelfeir** [comment] 2019-09-15 12:57
Another comment about Xcode: Something I had never seen before. I just recently got a new 2019 MacBook Air (yay me!) and was doing Catalina + Xcode 11 from scratch. xcodebuild -license was just hanging when I attempted to run it after installing command line tools: same with gcc, clang, etc.

It was first necessary to open Xcode.app manually by hand and have it be "verified". This process took FOREVER -- over 30 minutes.

**Comment by baelfeir** [comment] 2019-09-15 13:12
> > Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
> > Reading Package Lists...
> > Building Dependency Tree...
> > E: Some index files failed to download, they have been ignored, or old ones used instead.
> > ### execution of /sw/bin/apt-get-lockwait failed, exit code 100
> > WARNING: Failure while updating indexes.
> > ```
> > 
> > I think its just a mirror problem. I'll try another and play around.
> > ```
> 
> There's no 10.15 binary distribution yet, so it will error out to 404.

Yeah, I realized that after a bit of thinking. I bootstrapped again and set N to using binary dists.

**Comment by TheSin-** [comment] 2019-09-15 14:00
that is correct till things are official, during dev bin dist should always be N

**Comment by baelfeir** [comment] 2019-09-15 22:42
bootstrap at /opt/sw makes it all the way to failing at texi2html. Investigating.

**Comment by baelfeir** [comment] 2019-09-16 03:19
gettext-tools also needs gl_cv_func_ftello_works=yes added to the .info file

**Comment by baelfeir** [comment] 2019-09-16 04:41
looks like gmp6 fails on one of its unit-tests due to missing -lfl (I think, testing it now)

**Comment by baelfeir** [comment] 2019-09-18 17:07
FYI -- dpkg is failing with the same gl_cv_func_ftello_works problem I'll patchi and submit a pull request

**Comment by dmacks** [comment] 2019-09-18 17:20
On 9/18/19, 1:07 PM, "baelfeir" <notifications@github.com> wrote:
>
>    FYI -- dpkg is failing with the same gl_cv_func_ftello_works problem I'll patchi and submit a pull request

I wonder if there is an underlying bug in this detection (or else a need to hardcode the concept of "works":) in autoconf itself or some other central .m4 collection.

dan

-- 
Daniel Macks
dmacks@netspace.org

**Comment by nieder** [comment] 2019-09-18 18:16
The "ftello works" test program in [this comment](https://github.com/fink/fink/issues/197#issuecomment-528303426) comes from ftello.m4 which is from gnulib. The bug seems to be in a change on how putc() (doesn't) advances the file pointer from 10.15b5 to 10.15b6. Here's someone who got a bit more detail on the underlying problem: https://discourse.brew.sh/t/mac-os-10-15-catalina-issues/5001/24

Auto-patching ftello.m4 in tarballs would mean autoreconfing anything that uses autotools, right?

**Comment by baelfeir** [comment] 2019-09-21 02:50
With the latest set of 10.15 patches, bootstrapping and the initial update-all work great. again, I'm /opt/sw as my root.

**Comment by nieder** [comment] 2019-09-26 11:45
Submitted FB7326975 to apple.
Reopening because the gl_cv... parameter is not a fix but just a workaround.

**Comment by baelfeir** [comment] 2019-09-27 03:00
> Submitted FB7326975 to apple.
> Reopening because the gl_cv... parameter is not a fix but just a workaround.

Aye, of course. I saw your work going on on a different branch and didn't know if you needed this issue to be around still. I'll default to "let the maintainers maintain"

**Comment by j-lillibridge** [comment] 2019-10-01 17:44
The latest 10.15 developer beta 10, released yesterday (2019-09-30, solves the problem with getc/putc/ftell. Bootstrap now succeeds without the need for gl_cv_func_ftello_works=yes. However, gmp5 still fails with a segmentation violation. Have you made any progress getting gmp5 to build under 10.15?

**Comment by nieder** [comment] 2019-10-03 03:40
Nope. Still get a segfault when testing gmp5 on 10.15 and no idea how to debug.

**Comment by baelfeir** [comment] 2019-10-03 11:45
I do. I’ll see what I can uncover.

**Comment by j-lillibridge** [comment] 2019-10-03 15:04
Thanks @baelfeir & @nieder! Now that the bootstrap issue is fixed, I've succeeded in building gcc8. This required an "xcode-select -s Xcode-10.3". Three packages required 10.3 vs. 11.1: gmp5; libmpfr4; gcc8 itself. If you figure out what's causing the segfault errors, that would be great!

**Comment by baelfeir** [comment] 2019-10-03 18:44
j-lillibridge -- we already knew (nieder and others informed us) that it works with Xcode 10.3. The goal -- I believe, is to make it work with 10.15 and Xcode 11, thus this issue.

**Comment by j-lillibridge** [comment] 2019-10-03 20:34
Understood. Just to be clear: I had to use the older version of Xcode (10.3) when building those few packages under macOS 10.15 beta 10. I've had the same issue with Xcode 11.1 as with Xcode 11 - these packages wouldn't build in 10.15. Perhaps it's the SDK? Because using Xcode 11.0 under macOS 10.14/Mojave, these routines DO build properly...

**Comment by nieder** [comment] 2019-10-04 23:30
Here's a possible workaround/fix for gmp. Can someone with 10.15 add `-fno-stack-check` to ConfigureParams for gmp5.info?

**Comment by baelfeir** [comment] 2019-10-05 02:43
bootstrap finished for the first time for me using /opt/sw,

Xcode:

baelfeir:~ root# xcodebuild -version
Xcode 11.2
Build version 11B41

System Version:	macOS 10.15 (19A582a)

However, it looks like init.sh/pathsetup.sh aren't modified to recognize Apple's new obsession with zsh. I'm playing around with that now, so I can get at gmp5.

**Comment by baelfeir** [comment] 2019-10-05 03:31
============================================================================
Testsuite summary for GNU MP 6.1.2
============================================================================
# TOTAL: 20
# PASS:  20
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

well done, nieder!

baelfeir:libs root# diff -u gmp5.info gmp5.info.orig
--- gmp5.info   2019-10-04 22:30:22.000000000 -0500
+++ gmp5.info.orig      2019-10-04 22:30:06.000000000 -0500
@@ -16,7 +16,7 @@
 # gcc4.0 (>= 4.0.1-1)
 Conflicts: gmp, gmp-64bit, gmp5, gmp5-64bit
 Replaces: gmp, gmp-64bit, gmp5, gmp5-64bit
-SetCPPFLAGS: -fexceptions
+SetCPPFLAGS: -fexceptions -fno-stack-check
 # $host_build_override
 ConfigureParams: <<
   ABI=$ABI \
baelfeir:libs root#

**Comment by nieder** [comment] 2019-10-06 11:12
libmpfr4 and libmpfr6 also build now when using -fno-stack-check in SetCPPFLAGS (SetCFLAGS might be more appropriate, but same result).

The upstream tracking for gcc on 10.15/Xcode11 is: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90835

**Comment by baelfeir** [comment] 2019-10-07 20:12
Thanks! I’m watching the GCC thread and might want to gently suggest that the “upstream” fix he mentioned in the released Xcode 11 is probably still busted, since the problems outlined are still present Xcode 11.1 — maybe even the currently posted Xcode 11.2 beta.

Btw — If you’re interested, I’ll gpg you my Apple developer account ( the paid one ) and you can play around with all the toys.

**Comment by nieder** [comment] 2019-10-08 01:54
The gcc failure persists with 11.2beta. Haven't upgraded to 10.15final yet though.

**Comment by j-lillibridge** [comment] 2019-10-22 13:53
Thanks for the 'no-stack-check' workaround, to get gmp5 & libmpfr4 to compile. Unfortunately, gcc8 still fails due to header issues in the macOS 10.15 SDK. I wanted to document my progress on this, even if it reiterates what @baelfeir & @nieder have already provided:


macOS version: 10.15.0 Update (19A602)
Xcode CLI version: 11.0.0.0.1.1567737322
Xcode-beta app version: Xcode 11.2 beta 2 (Build version 11B44)


The no-stack-check fix:

libs/gmp5.info:

SetCPPFLAGS: -fexceptions -fno-stack-check

libs/libmpfr4.info

        if [ "%type_raw[-64bit]" == "-64bit" ]; then
                export CC="gcc -m64 -fno-stack-check"
        else
                export CC="gcc -fno-stack-check"
        fi


And finally, after adding 10.15 to the Distribution list in gcc8-10.14.5.info, the failure to compile remains:

In file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:110,
                 from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:66,
                 from ../../../gcc-8.3.0/libgomp/libgomp-plugin.c:29:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h: In function 'getiopolicy_np':
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:447:34: error: expected declaration specifiers before '__OSX_AVAILABLE_STARTING'

 int     getiopolicy_np(int, int) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by baelfeir** [comment] 2019-10-24 22:24
how close is 0.46 atm? don't worry -- not rushing. I've been cloning from here and all is well save, well, whatever is not well. was just curious.

**Comment by nieder** [comment] 2019-10-25 10:41
gmp5/libmpfr* fixed in git by commit [b8afe31c](https://github.com/fink/fink-distributions/commit/b8afe31cf1f082d263ffe1f10457b4718ad71d31).

I'm going to close this now because we can successfully bootstrap on 10.15 and Xcode11. The remaining problems that I'm aware of are package specific (not specifically related to the fink tool itself) and should be dealt with in [fink/fink-distributions](https://github.com/fink/fink-distributions).

If there's some part of the fink tool itself or bootstrapping that's broken on 10.15, then please comment so we can reopen.

**Closed by nieder** 2019-10-25 10:41 UTC
Labels: Bootstrap

**Comment by sci345** [comment] 2020-10-07 17:21
Installing fink-045.2 manually using https://www.finkproject.org/download/srcdist.php. I have macOS Catalina 10.15.6, Xcode 12. Running into this error when running  ./bootstrap

Downloading the indexes of available packages in the binary distribution.
/opt/sw/bin/apt-get-lockwait -q update
Err http://bindist.finkmirrors.net stable/main Packages
  404 Not Found
Ign http://bindist.finkmirrors.net stable/main Release
Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
Reading Package Lists...
Building Dependency Tree...
E: Some index files failed to download, they have been ignored, or old ones used instead.
### execution of /opt/sw/bin/apt-get-lockwait failed, exit code 100
WARNING: Failure while updating indexes.

ERROR: Bootstrap phase 2 failed!-bash: New: command not found

Any thoughts on how to proceed?

**Comment by TheSin-** [comment] 2020-10-07 17:38
When asked to use binary distribution say no

**Comment by sci345** [comment] 2020-10-07 20:56
> When asked to use binary distribution say no

To do that, would I have to uninstall the failed attempt and reinstall fink? I'm unsure how to change the use binary distribution at my stage of the installation process. Thank you for your time!

**Comment by TheSin-** [comment] 2020-10-07 21:16
oh I thought you were bootstrapping, then disable it in the fink.conf.  There is no 10.15 binary diet that is the issue.  The test for it needs to become non fatal to avoid this, but in the mean time just turn it off in /opt/sw/etc/fink.conf

**Comment by akhansen** [comment] 2020-10-07 21:25
One additional thing you should do is run _/opt/sw/bin/pathsetup.sh_, because the error occurred before this final step.  This will set up your Fink environment.

**Comment by sci345** [comment] 2020-10-07 23:45
> One additional thing you should do is run _/opt/sw/bin/pathsetup.sh_, because the error occurred before this final step. This will set up your Fink environment.

When I run /opt/sw/bin/pathsetup.sh it gives me the error below

DOM-0WSML85-LT:fink-0.45.2 Sharline$ /opt/sw/bin/pathsetup.sh
/Users/Sharline/.bash_profile: line 4: 1: command not found
/Users/Sharline/.bash_profile: line 5: .bash_profile.pysave: command not found
/opt/sw/bin/pathsetup.sh: line 261: [: too many arguments
/opt/sw/bin/pathsetup.sh: line 263: [: too many arguments
/opt/sw/bin/pathsetup.sh: line 265: [: too many arguments
chown: /Users/Sharline: No such file or directory
chown: 1: No such file or directory
chown: 2/.profile: No such file or directory
/Users/Sharline/.bash_profile: line 4: 1: command not found
/Users/Sharline/.bash_profile: line 5: .bash_profile.pysave: command not found
OK

I'm even trying to uninstall fink so I can start over, but since the installation process failed at the ./bootstrap command fink isn't actually fully installed and I cant find a straight forward way to delete it.

**Comment by TheSin-** [comment] 2020-10-07 23:57
sudo rm -rf /opt/sw

Close your terminal and reopen, it’ll be gone
